export const navItems = [
  { title: "Home", href: "#home" },
  { title: "Services", href: "#services" },
  { title: "About me", href: "#about" },
  { title: "Skills", href: "#skills" },
  { title: "Portfolio", href: "#portfolio" },
  { title: "Contact me", href: "#contact" },
];

// All Social Links

export const socialLink = [
  {
    id: 1,
    name: "Facebook",
    url: "https://facebook.com/yourprofile",
    icon: "FaFacebookF",
  },
  {
    id: 2,
    name: "Twitter",
    url: "https://twitter.com/yourprofile",
    icon: "FaXTwitter",
  },
  {
    id: 3,
    name: "Instagram",
    url: "https://instagram.com/yourprofile",
    icon: "FaInstagram",
  },
  {
    id: 4,
    name: "LinkedIn",
    url: "https://linkedin.com/in/yourprofile",
    icon: "FaLinkedinIn",
  },
  {
    id: 5,
    name: "GitHub",
    url: "https://github.com/yourprofile",
    icon: "FaGithub",
  },
];

export const portfolioData = {
  all: [
    // Web projects
    {
      id: 1,
      title: "Web Project 1",
      category: "web",
      image: "/project1.jpg",
      githubUrl: "https://github.com/username/web-project1",
      liveUrl: "https://web-project1-live.com",
    },
    {
      id: 2,
      title: "Web Project 2",
      category: "web",
      image: "/project2.jpg",
      githubUrl: "https://github.com/username/web-project2",
      liveUrl: "https://web-project2-live.com",
    },
    {
      id: 3,
      title: "Web Project 3",
      category: "web",
      image: "/project3.jpg",
      githubUrl: "https://github.com/username/web-project3",
      liveUrl: "https://web-project3-live.com",
    },
    {
      id: 4,
      title: "Web Project 4",
      category: "web",
      image: "/project4.jpg",
      githubUrl: "https://github.com/username/web-project4",
      liveUrl: "https://web-project4-live.com",
    },
    {
      id: 5,
      title: "Web Project 5",
      category: "web",
      image: "/project5.jpg",
      githubUrl: "https://github.com/username/web-project5",
      liveUrl: "https://web-project5-live.com",
    },
    {
      id: 6,
      title: "Web Project 6",
      category: "web",
      image: "/project6.jpg",
      githubUrl: "https://github.com/username/web-project6",
      liveUrl: "https://web-project6-live.com",
    },

    // App projects
    {
      id: 7,
      title: "App Project 1",
      category: "app",
      image: "/project1.jpg",
      githubUrl: "https://github.com/username/app-project1",
      liveUrl: "https://app-project1-live.com",
    },
    {
      id: 8,
      title: "App Project 2",
      category: "app",
      image: "/project2.jpg",
      githubUrl: "https://github.com/username/app-project2",
      liveUrl: "https://app-project2-live.com",
    },
    {
      id: 9,
      title: "App Project 3",
      category: "app",
      image: "/project3.jpg",
      githubUrl: "https://github.com/username/app-project3",
      liveUrl: "https://app-project3-live.com",
    },
    {
      id: 10,
      title: "App Project 4",
      category: "app",
      image: "/project4.jpg",
      githubUrl: "https://github.com/username/app-project4",
      liveUrl: "https://app-project4-live.com",
    },
    {
      id: 11,
      title: "App Project 5",
      category: "app",
      image: "/project5.jpg",
      githubUrl: "https://github.com/username/app-project5",
      liveUrl: "https://app-project5-live.com",
    },
    {
      id: 12,
      title: "App Project 6",
      category: "app",
      image: "/project6.jpg",
      githubUrl: "https://github.com/username/app-project6",
      liveUrl: "https://app-project6-live.com",
    },

    // Design projects
    {
      id: 13,
      title: "Design Project 1",
      category: "design",
      image: "/project1.jpg",
      githubUrl: "https://github.com/username/web-project7",
      liveUrl: "https://web-project7-live.com",
    },
    {
      id: 14,
      title: "Design Project 2",
      category: "design",
      image: "/project2.jpg",
      githubUrl: "https://github.com/username/web-project8",
      liveUrl: "https://web-project8-live.com",
    },
    {
      id: 15,
      title: "Design Project 3",
      category: "design",
      image: "/project3.jpg",
      githubUrl: "https://github.com/username/web-project9",
      liveUrl: "https://web-project9-live.com",
    },
    {
      id: 16,
      title: "Design Project 4",
      category: "design",
      image: "/project4.jpg",
      githubUrl: "https://github.com/username/web-project10",
      liveUrl: "https://web-project10-live.com",
    },
    {
      id: 17,
      title: "Design Project 5",
      category: "design",
      image: "/project5.jpg",
      githubUrl: "https://github.com/username/web-project11",
      liveUrl: "https://web-project11-live.com",
    },
    {
      id: 18,
      title: "Design Project 6",
      category: "design",
      image: "/project6.jpg",
      githubUrl: "https://github.com/username/web-project12",
      liveUrl: "https://web-project12-live.com",
    },

    // Branding projects
    {
      id: 19,
      title: "Branding Project 1",
      category: "branding",
      image: "/project1.jpg",
      githubUrl: "https://github.com/username/web-project13",
      liveUrl: "https://web-project13-live.com",
    },
    {
      id: 20,
      title: "Branding Project 2",
      category: "branding",
      image: "/project2.jpg",
      githubUrl: "https://github.com/username/web-project14",
      liveUrl: "https://web-project14-live.com",
    },
    {
      id: 21,
      title: "Branding Project 3",
      category: "branding",
      image: "/project3.jpg",
      githubUrl: "https://github.com/username/web-project15",
      liveUrl: "https://web-project15-live.com",
    },
    {
      id: 22,
      title: "Branding Project 4",
      category: "branding",
      image: "/project4.jpg",
      githubUrl: "https://github.com/username/web-project16",
      liveUrl: "https://web-project16-live.com",
    },
    {
      id: 23,
      title: "Branding Project 5",
      category: "branding",
      image: "/project5.jpg",
      githubUrl: "https://github.com/username/web-project17",
      liveUrl: "https://web-project17-live.com",
    },
    {
      id: 24,
      title: "Branding Project 6",
      category: "branding",
      image: "/project6.jpg",
      githubUrl: "https://github.com/username/web-project18",
      liveUrl: "https://web-project18-live.com",
    },
  ],
};
